export enum ResultActionType{
    FETCH_SEARCH_PROCESS = 'FETCH_SEARCH',
    FETCH_SEARCH_SUCCESS = 'FETCH_SEARCH_SUCCESS',
    FETCH_NEWS_SUCCESS = 'FETCH_NEWS_SUCCESS',
    FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS',
}